In [6]:
import math
import numpy as np
def sigmoid(z):
    return 1/(1+math.exp(-z))
print(sigmoid(0))
class Perceptor(object):
    def __init__(self,w,b):
        self.w=w
        self.b=b
    def __call__(self,x):
        return sigmoid(np.dot(x,self.w)+self.b)
pe=Perceptor([1,2,3],-4)
output=pe([1,0,1])
print(output)
output=pe([1,1,0])
print(output)

0.5
0.5
0.2689414213699951


In [9]:
import numpy as np
import pandas as pd
df = pd.read_csv('C:\\Users\\MECHREVO\\Desktop\\BeijingPM20100101_20151231.csv', encoding='UTF-8', usecols=[1, 2, 3, 4, 5, 6, 7, 8])
data_arr=np.array(df.dropna(axis = 0))
hour_val=np.mean(data_arr[:,5:],axis=1)
print(data_arr)
n_1=hour_val.shape[0]
n_2=hour_val[hour_val>150].shape[0]
print(n_2/n_1)
n_3=hour_val[(hour_val>75) & (hour_val<=150)].shape[0]
print(n_3/n_1)
n_4 = hour_val[(hour_val > 35) & (hour_val <= 75)].shape[0]
print(n_4/n_1)
n_5 = hour_val[hour_val <= 35].shape[0]
print(n_5/n_1)
years=np.unique(data_arr[:,0])
print(years)


for year in years:
    year_data_arr=data_arr[data_arr[:,0]==year]  
    month_list=np.unique(year_data_arr[:,1])
    print("---------------------------------------------")
    for month in month_list:
        month_data_arr=year_data_arr[year_data_arr[:,1]==month]
        mean_vals=np.mean(month_data_arr[:,5:],axis=0).tolist()
        print(mean_vals)



[[2013.    3.    5. ...  117.  166.  140.]
 [2013.    3.    5. ...  131.  165.  152.]
 [2013.    3.    5. ...  141.  173.  128.]
 ...
 [2015.   12.   31. ...  157.  199.  149.]
 [2015.   12.   31. ...  171.  231.  196.]
 [2015.   12.   31. ...  204.  242.  221.]]
0.1723346759802172
0.26956610411461784
0.24611227247233977
0.3119869474328252
[2013. 2014. 2015.]
---------------------------------------------
[117.99354838709678, 128.4725806451613, 116.1774193548387]
[64.298937784522, 63.165402124430955, 56.88770864946889]
[91.35816618911174, 101.55014326647564, 77.11174785100286]
[110.01160092807424, 119.17169373549883, 108.27146171693735]
[72.19110378912686, 85.35090609555189, 74.67051070840198]
[63.986301369863014, 69.77168949771689, 64.64687975646879]
[83.79607250755286, 82.89577039274924, 80.97129909365559]
[102.78525641025641, 101.52403846153847, 94.6923076923077]
[83.16338028169014, 84.2338028169014, 83.55211267605634]
[87.7453505007153, 92.02718168812589, 89.99570815450643]
--------