In [1]:
import math
import numpy as np

def sigmoid(z):
    return 1/(1+math.exp(-z))
print(sigmoid(0))

class Perceptor(object):
    def __init__(self,w,b):
        self.w=w
        self.b=b
    def __call__(self,x):
        return sigmoid(np.dot(x,self.w)+self.b)
    
p=Perceptor([1,2,3],-4)
output=p([1,0,1])
print(output)
output=p([1,1,0])
print(output)

0.5
0.5
0.2689414213699951


In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('BeijingPM20100101_20151231.csv', encoding='UTF-8', usecols=[1, 2, 3, 4, 5, 6, 7, 8])
data_arr=np.array(df.dropna(axis = 0))
hour_val=np.mean(data_arr[:,5:],axis=1)
print(data_arr)

n_hours=hour_val.shape[0]

# heavy
n_heavy_hours=hour_val[hour_val>150].shape[0]
print(n_heavy_hours/n_hours)
# medium
n_medium_hours=hour_val[(hour_val>75) & (hour_val<=150)].shape[0]
print(n_medium_hours/n_hours)
# light
n_light_hours = hour_val[(hour_val > 35) & (hour_val <= 75)].shape[0]
print(n_light_hours/n_hours)
# good
n_good_hours = hour_val[hour_val <= 35].shape[0]
print(n_good_hours/n_hours)




[[2013.    3.    5. ...  117.  166.  140.]
 [2013.    3.    5. ...  131.  165.  152.]
 [2013.    3.    5. ...  141.  173.  128.]
 ...
 [2015.   12.   31. ...  157.  199.  149.]
 [2015.   12.   31. ...  171.  231.  196.]
 [2015.   12.   31. ...  204.  242.  221.]]
0.1723346759802172
0.26956610411461784
0.24611227247233977
0.3119869474328252


In [7]:
years=np.unique(data_arr[:,0])
print(years)
for year in years:
    # 获取当前年份数据
    year_data=data_arr[data_arr[:,0]==year]  
     # 获取数据的月份
    month_list=np.unique(year_data[:,1])
    y=str(int(year))
    print("----------"+y+"----------")
    for month in month_list:
        # 获取月份的所有数据
        month_data=year_data[year_data[:,1]==month]
           # 计算当前月份PM的均值
        mean_vals=np.mean(month_data[:,5:],axis=0).tolist()
        print(mean_vals)
        

[2013. 2014. 2015.]
----------2013----------
[117.99354838709678, 128.4725806451613, 116.1774193548387]
[64.298937784522, 63.165402124430955, 56.88770864946889]
[91.35816618911174, 101.55014326647564, 77.11174785100286]
[110.01160092807424, 119.17169373549883, 108.27146171693735]
[72.19110378912686, 85.35090609555189, 74.67051070840198]
[63.986301369863014, 69.77168949771689, 64.64687975646879]
[83.79607250755286, 82.89577039274924, 80.97129909365559]
[102.78525641025641, 101.52403846153847, 94.6923076923077]
[83.16338028169014, 84.2338028169014, 83.55211267605634]
[87.7453505007153, 92.02718168812589, 89.99570815450643]
----------2014----------
[106.0098730606488, 103.33004231311706, 107.71086036671367]
[143.07119741100323, 138.86893203883494, 144.03074433656957]
[98.71291208791209, 100.60027472527473, 99.53846153846153]
[89.04088586030664, 95.57921635434413, 86.31856899488926]
[63.061654135338344, 58.78195488721804, 63.28270676691729]
[57.82436260623229, 63.53541076487252, 56.9220963